# Netlify configuration for Vite + Vue SPA
[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/lexone"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/lexis-one-terms"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/lexis-one-privacy"
  to = "/index.html"
  status = 200

# Catch-all SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For local Netlify dev
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# more info on configuring this file: https://ntl.fyi/file-based-build-config
